-- POSBAH SUPABASE RLS DISABLE & PRIVILEGES GRANTS
-- Copy and paste this script into your Supabase Dashboard SQL Editor, then click "RUN".

-- 1. Disable Row Level Security (RLS) on all PosBah tables
ALTER TABLE IF EXISTS local_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS outlets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_master_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_invoice_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_cashflow DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_payrolls DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_bahan_baku DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bmp_bahan_baku_item DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS print_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transaction_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activity_logs DISABLE ROW LEVEL SECURITY;

-- 2. Grant all privileges on all PosBah tables to service_role (used by VPS backend), anon, and authenticated roles (used by mobile client)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;

-- 3. Grant privileges on all sequences in schema public (important for auto-increment columns)
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
