ALTER TABLE outlets ADD COLUMN IF NOT EXISTS "isOpen" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE outlets ADD COLUMN IF NOT EXISTS "currentEmployee" TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS "payPeriod" TEXT NOT NULL DEFAULT 'MONTHLY';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS "lastPaidAt" BIGINT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN NOT NULL DEFAULT FALSE;
