ALTER TABLE bmp_clients ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE bmp_invoices ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE bmp_cashflow ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE bmp_bahan_baku ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE bmp_bahan_baku_item ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN DEFAULT FALSE;
