SELECT 'local_users' AS tbl, COUNT(*) FROM local_users WHERE email='bahteramulyap@gmail.com' UNION ALL
SELECT 'tenants', COUNT(*) FROM tenants WHERE id='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'outlets', COUNT(*) FROM outlets WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'employees', COUNT(*) FROM employees WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'products', COUNT(*) FROM products WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'customers', COUNT(*) FROM customers WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_clients', COUNT(*) FROM bmp_clients WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_master_products', COUNT(*) FROM bmp_master_products WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_settings', COUNT(*) FROM bmp_settings WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_employees', COUNT(*) FROM bmp_employees WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'print_settings', COUNT(*) FROM print_settings WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'transactions', COUNT(*) FROM transactions WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_invoices', COUNT(*) FROM bmp_invoices WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_bahan_baku', COUNT(*) FROM bmp_bahan_baku WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_cashflow', COUNT(*) FROM bmp_cashflow WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_payrolls', COUNT(*) FROM bmp_payrolls WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'transaction_items', COUNT(*) FROM transaction_items WHERE "transactionId" IN (SELECT id FROM transactions WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com') UNION ALL
SELECT 'bmp_products', COUNT(*) FROM bmp_products WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_invoice_payments', COUNT(*) FROM bmp_invoice_payments WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_bahan_baku_item', COUNT(*) FROM bmp_bahan_baku_item WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_product_stocks', COUNT(*) FROM bmp_product_stocks WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_stock_ledger', COUNT(*) FROM bmp_stock_ledger WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'bmp_production_logs', COUNT(*) FROM bmp_production_logs WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com' UNION ALL
SELECT 'activity_logs', COUNT(*) FROM activity_logs WHERE "tenantId"='ten_premium_bahteramulyap_gmail_com';
